### ISSUE TITLE
Creator’s @id

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/requirements-datasets#12]
@coret Currently we have no `@id` for `schema:creator` (only a `schema:url`). Should we at least recommend or perhaps even require the creator’s `@id`?

This is quite relevant because I see Van Gogh Worldwide [adopting our standards](https://github.com/vangoghworldwide/delafaille/blob/master/dataset.jsonld#L8-L12), without the `@id`.

**Comment by coret** [comment]
Agreed, the Register wants to work with information about datasets _and_ organisations. 
An `@id` certainly should be part of a schema:creator **and** schema:publisher (I think for both schema:Organisation as well as schema:Person).

Will it be a problem when there is no `@id`? Not sure about recommending or requiring this property yet.

**Comment by ddeboer** [comment]
Both [organisation’s IRI and URL are still required]((https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/#organization-information)), which is very confusing.

@coret I propose the evil `schema:url` completely and make `publisher’s @id` required.
