### ISSUE TITLE
Update conceptual model 

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/requirements-datasets#50]
- add link from DataCatalog to Organization/Person with publisher "label"
- change publisher "label" from Dataset into publisher/creator
- is license an IRI? In example it's a literal...

**Comment by ddeboer** [comment]
> is license an IRI? In example it's a literal...

In which example?

**Comment by ddeboer** [comment]
See #51. I kept the label ‘publisher’ because the simple diagram is meant to only show _required_ relations; publisher is required whereas creator is not.

**Comment by coret** [comment]
> > is license an IRI? In example it's a literal...
> 
> In which example?

I was referring to [Example 3](https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/#dataset-license):
```
{
  "@context": "https://schema.org/",
  "@type": "Dataset",
  "license": "http://creativecommons.org/publicdomain/zero/1.0/"
}
```

But it's my bad, I thought you had to write `"license":{"@id":"http://creativecommons.org/publicdomain/zero/1.0/"}` to indicate an IRI, but confusingly `"license": "http://creativecommons.org/publicdomain/zero/1.0/"` is the same, but short-hand. Note to self: If you really wanted a literal, you'd have to write `"license":{"@value":"http://creativecommons.org/publicdomain/zero/1.0/"}`.
