### ISSUE TITLE
Add schema:contactPoint

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/requirements-datasets#55]
Add `schema:contactPoint` to the publisher & creator `schema:Organization` and make at least its `schema:name`,  `schema:email` and/or `schema:url` required. This is very useful for client applications that want to show a link like: ‘you can report errors in this data at …’.

**Comment by coret** [comment]
+1

Also for the Dataset Register support team this information (especially the publisher contactPoint) is important. 
When there's an issue with the dataset description, the support team needs to know who to contact at the publisher!

```
"publisher": {
		"@id": "https://example.com/",
		"@type": "Organization",
		"name": "Example organisation",
		"contactPoint": {
			"@type": "ContactPoint",
			"name": "A. Person",
			"email": "info@example.com",
		}
	},
```

#LessonLearnedHackaLOD2020
