### ISSUE TITLE
Example of a 'term'

### ISSUE THREAD

**Issue by ivozandhuis** [netwerk-digitaal-erfgoed/requirements-datasets#7]
https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/#definitions
Better not use '1642' as a term. Suggestion: 'Dutch Golden Age'.

**Comment by ddeboer** [comment]
We decided to remove any requirements concerning the contents of the datasets (#25 and #20). This includes the the term and term sources definitions, so this issue is no longer relevant.
